name: Auto Assign Reviewers

on:
  pull_request:
    types: [opened, reopened]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    
    permissions:
      pull-requests: write
    
    steps:
    - name: Checkout CODEOWNERS
      uses: actions/checkout@v3
    
    - name: Assign reviewers
      uses: kentaro-m/auto-assign@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: .github/auto-assign.yml
      continue-on-error: true
    
    - name: Assignment Success
      run: echo "✅ Reviewers assigned to pull request!"