name: Deploy to Production

on: workflow_dispatch

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy workflow running
        run: echo "✅ This workflow is active: deploy-prod"
