name: Basic CI Template

on:
  workflow_call:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Called from basic-ci template
        run: echo "✅ This reusable workflow is active: basic-ci"
